name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Client unit tests
        run: docker run isso-js-testbed npm run test-unit
      - name: Client integration tests
        run: docker run isso-js-testbed npm run test-integration
